### PR TITLE
fix nil errors

### PR DESCRIPTION
**Pull request by Techbot121**

### CODE REVIEW

**Comment by Techbot121** [comment]
also it would be nice if the debug print from the slam weapon would be removed. You can always use it when you're on the server but for stuff added to a server it's really annoying.

**Comment by rebel1324** [comment]
Wait what? I submitted the git
2017. 2. 11. 오후 9:34에 "Techbot121" <notifications@github.com>님이 작성:

**Comment by Techbot121** [comment]
caps added it to the server and now we're also getting the errors 🤔 
https://github.com/PAC3-Server/ServerContent/commit/48d7c18e775e15b0b6bfa37118bb140accdac3ee

**Comment by rebel1324** [comment]
I mean fixed version should be online
2017. 2. 12. 오전 12:36에 "Techbot121" <notifications@github.com>님이 작성:

**Pull request closed without merging**
